### PR TITLE
avoid pulling in slf4j and log4j through commmon-utils

### PR DESCRIPTION
**Pull request by xvrl**

### CODE REVIEW

**Comment by cmccabe** [comment]
What's the rationale?

**Comment by xvrl** [comment]
@cmccabe when we ship a library we should not be imposing the logging backend, i.e. we should depend only on slf4j-api and let the user decide what logging implementation they are going to use.

**Comment by stanislavkozlovski** [comment]
LGTM and the rationale is solid

**Comment by cmccabe** [comment]
Thanks for the explanation.  LGTM.

**Pull request merged**
