### PR TITLE
update easymock for Java 16 support

### PR DESCRIPTION
**Pull request by xvrl**
Release notes: https://github.com/easymock/easymock/releases/tag/easymock-4.3

### CODE REVIEW

**Review by xli1996 — APPROVED** [review]
That upgrade seems break blueway as downstream.

**Comment by xvrl** [comment]
downstream failures have been addressed

**Review by xli1996 — APPROVED** [review]

**Comment by andrewegel** [comment]
I see a build failure in blueway which looks related to this change:

```
16:02:43  [INFO] -------------------------------------------------------------
16:02:43  [ERROR] COMPILATION ERROR : 
16:02:43  [INFO] -------------------------------------------------------------
16:02:43  [ERROR] /home/jenkins/workspace/confluentinc-pr_common_PR-355/blueway-master/control-center/src/test/java/io/confluent/controlcenter/kafka/DynamicClusterManagerTest.java:[252,18] incompatible types: org.easymock.IMockBuilder<java.lang.Object> cannot be converted to org.easymock.IMockBuilder<io.confluent.controlcenter.kafka.DynamicClusterManager>
16:02:43  [ERROR] /home/jenkins/workspace/confluentinc-pr_common_PR-355/blueway-master/control-center/src/test/java/io/confluent/controlcenter/kafka/StaticClusterManagerTest.java:[344,18] incompatible types: org.easymock.IMockBuilder<java.lang.Object> cannot be converted to org.easymock.IMockBuilder<io.confluent.controlcenter.kafka.StaticClusterManager>
16:02:43  [INFO] 2 errors 
```

**Review by andrewegel — APPROVED** [review]
> downstream failures have been addressed

I see the related change - Lets get a Green CI check and then merge.

**Comment by andrewegel** [comment]
Passed: https://jenkins.confluent.io/job/confluentinc-pr/job/common/job/PR-355/5/

**Pull request merged**
