### PR TITLE
Update zkclient to 0.9

### PR DESCRIPTION
**Pull request by ijuma**
This is the version that Kafka 0.10.1.0 uses.

### CODE REVIEW

**Comment by ijuma** [comment]
Review by @ewencp

**Comment by miguno** [comment]
Thanks for being so thorough, @ijuma !

**Comment by pxLi** [comment]
The old zkClient version(0.5) is really annoying.
Will anyone merge this PR? Thanks!

**Comment by ewencp** [comment]
@ijuma This is quite outdated and I think we now use a newer version in Kafka, but do you want to update this PR and get it included for the next release?

**Comment by ijuma** [comment]
@ewencp done.

**Comment by ewencp** [comment]
@ijuma Do you want to target it at `trunk` or `3.1.x`? I'm fine with either one, just not sure if you actually intended it to still be trunk since that won't make it into the next release.

**Comment by ewencp** [comment]
In any case, LGTM if this is the target you want. If not, we can always put it in another PR and you can implicitly have the LGTM based on this branch + PR builder passing :)

**Comment by ijuma** [comment]
@ewencp Sorry, I wasn't sure if you were OK with having 3.1.x as the target. Seems like you are, so updated the target branch.

**Comment by ewencp** [comment]
retest this please

**Comment by ewencp** [comment]
@ijuma Yeah, at this point I'm still fine with it -- we'll have time to have system tests, packaging smoke tests, etc run, so I don't see any issue. I triggered another test run since it looks like the change in target branch wasn't picked up automatically. Assuming this passes, still LGTM.

**Pull request merged**
