### PR TITLE
Upgrade checkstyle and maven compiler plugin, enforce consistent EOF line endings

### PR DESCRIPTION
**Pull request by xvrl**
* Upgrade checkstyle and maven checkstyle plugin to latest versions
* Upgrade maven compiler plugin to support Java 10
* Enforce consistent newlines at end of files

### CODE REVIEW

**Comment by ijuma** [comment]
Won't this cause a bunch of failures?

**Comment by xvrl** [comment]
@ijuma we might as well fix them, shouldn't be too hard

**Comment by xvrl** [comment]
sure it's debatable, as are some other whitespace formatting decisions, like an empty line after class declarations. As with everything it's about consistency. At the very least it avoids git warnings about missing newlines and makes diffs display more cleanly when only appending to a file.

**Comment by ewencp** [comment]
@xvrl Can we close this out, or update and get it committed? It looks like we've got the same or newer versions now for all the version updates. The only thing currently missing from master is the newline setting for checkstyle.

**Pull request closed without merging**
