### PR TITLE
Allow to compile on macOS Mojave

### PR DESCRIPTION
**Pull request by msilvestre**

### CODE REVIEW

**Comment by msilvestre** [comment]
[clabot:check]

**Comment by ewencp** [comment]
Can you explain why this is necessary? We have a lot of people who build this on Mojave without this addition.

**Comment by msilvestre** [comment]
hmmm, maybe you are right.

When I was compiling I got an error that was resolved with that fix.
I've tried to compile today, again without the posix and now I got another error :-/
Actually I now I got this error with or without posix:

`Cannot resolve org.apache.kafka:connect-api:5.5.0-ccs-SNAPSHOT`

**Comment by ewencp** [comment]
This repo depends on Kafka, you'll need to build the master branch from confluentinc/kafka to provide that dependency for a SNAPSHOT build.

**Comment by bagipriyank** [comment]
is this the error 
```
[INFO] Building zip: /Users/pbagrecha/sr/confluentinc/common/package/target/common-package-5.5.0-SNAPSHOT-package.zip
[WARNING] Cannot include project artifact: io.confluent:common-package:pom:5.5.0-SNAPSHOT; it doesn't have an associated file or directory.
[INFO] Building tar: /Users/pbagrecha/sr/confluentinc/common/package/target/common-package-5.5.0-SNAPSHOT-package.tar.gz
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for common 5.5.0-SNAPSHOT:
[INFO]
[INFO] assembly-plugin-boilerplate ........................ SUCCESS [  0.682 s]
[INFO] Build Tools ........................................ SUCCESS [  0.609 s]
[INFO] common ............................................. SUCCESS [  1.491 s]
[INFO] utils .............................................. SUCCESS [  0.752 s]
[INFO] metrics ............................................ SUCCESS [  1.997 s]
[INFO] config ............................................. SUCCESS [  1.539 s]
[INFO] common-logging ..................................... SUCCESS [  2.221 s]
[INFO] confluent-log4j-extensions ......................... SUCCESS [  1.724 s]
[INFO] confluent-log4j2-extensions ........................ SUCCESS [  1.943 s]
[INFO] package ............................................ FAILURE [  0.682 s]
[INFO] Common ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.027 s
[INFO] Finished at: 2019-12-20T12:55:33-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (package-assembly) on project common-package: Execution package-assembly of goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single failed: group id '2069044465' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :common-package
```

**Comment by arvindth** [comment]
From https://stackoverflow.com/questions/33819438/maven-assembly-plugin-group-id-1377585961-is-too-big-error it looks like it's actually possible for random users to have groupIds that are bigger than can be handled by the default maven assembly configuration. In such cases, it looks like adding this change can indeed help, at least when there are errors like @bagipriyank is seeing:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (package-assembly) on project common-package: Execution package-assembly of goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single failed: group id '2069044465' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit -> [Help 1]
```
Not sure if this is the same issue faced by @msilvestre though. Also doesn't appear to be Mojave specific, just random based on the group id assigned by the OS.

**Pull request closed without merging**
