### PR TITLE
ST-5293: Upgrading jackson because of CVE

### PR DESCRIPTION
**Pull request by elismaga**
Upgrading the version of jackson to resolve the cve.

### CODE REVIEW

**Review by acourtneybrown — APPROVED** [review]
Looks fine other than the build error 😦 

A little spelunking in the [Jenkins build log](https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/common/job/PR-328/1/consoleFull) turned up:

```
04:24:54  [INFO] -------------------------------------------------------------
[2021-04-28T04:24:54.897Z] [ERROR] COMPILATION ERROR : 
04:24:54  [INFO] -------------------------------------------------------------
[2021-04-28T04:24:54.898Z] [ERROR] /home/jenkins/workspace/ntinc_Contributors_common_PR-328/metadata-service-6.2.x/rbac-api-server/src/main/java/org/glassfish/jersey/logging/MDSLoggingFilter.java:[42,5] constructor LoggingInterceptor in class org.glassfish.jersey.logging.LoggingInterceptor cannot be applied to given types;
04:24:54    required: org.glassfish.jersey.logging.LoggingFeature.LoggingFeatureBuilder
04:24:54    found: java.util.logging.Logger,java.util.logging.Level,org.glassfish.jersey.logging.LoggingFeature.Verbosity,int
04:24:54    reason: actual and formal argument lists differ in length
04:24:54  [INFO] 1 error
04:24:54  [INFO] -------------------------------------------------------------
04:24:54  [INFO] ------------------------------------------------------------------------
04:24:54  [INFO] Reactor Summary for metadata-service 6.2.0-99999:
04:24:54  [INFO] 
04:24:54  [INFO] metadata-service ................................... SUCCESS [  5.458 s]
04:24:54  [INFO] mds-test-tools ..................................... SUCCESS [  0.994 s]
04:24:54  [INFO] testing-ldap ....................................... SUCCESS [  4.724 s]
04:24:54  [INFO] testing-ldap-cli ................................... SUCCESS [  3.160 s]
04:24:54  [INFO] rbac-db ............................................ SUCCESS [  5.749 s]
04:24:54  [INFO] rbac-api-server .................................... FAILURE [  4.976 s]
04:24:54  [INFO] rbac-api-perf ...................................... SKIPPED
04:24:54  [INFO] ------------------------------------------------------------------------
04:24:54  [INFO] BUILD FAILURE
04:24:54  [INFO] ------------------------------------------------------------------------
04:24:54  [INFO] Total time:  25.497 s
04:24:54  [INFO] Finished at: 2021-04-28T04:24:54Z
04:24:54  [INFO] ------------------------------------------------------------------------
04:24:54  [INFO] [jenkins-event-spy] Generated /home/jenkins/workspace/ntinc_Contributors_common_PR-328@tmp/withMavend0d4df14/maven-spy-20210428-042428-8632614403887378325379.log
[2021-04-28T04:24:54.898Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project rbac-api-server: Compilation failure
[2021-04-28T04:24:54.898Z] [ERROR] /home/jenkins/workspace/ntinc_Contributors_common_PR-328/metadata-service-6.2.x/rbac-api-server/src/main/java/org/glassfish/jersey/logging/MDSLoggingFilter.java:[42,5] constructor LoggingInterceptor in class org.glassfish.jersey.logging.LoggingInterceptor cannot be applied to given types;
[2021-04-28T04:24:54.898Z] [ERROR]   required: org.glassfish.jersey.logging.LoggingFeature.LoggingFeatureBuilder
[2021-04-28T04:24:54.898Z] [ERROR]   found: java.util.logging.Logger,java.util.logging.Level,org.glassfish.jersey.logging.LoggingFeature.Verbosity,int
[2021-04-28T04:24:54.898Z] [ERROR]   reason: actual and formal argument lists differ in length
[2021-04-28T04:24:54.898Z] [ERROR] -> [Help 1]
[2021-04-28T04:24:54.898Z] [ERROR] 
[2021-04-28T04:24:54.898Z] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[2021-04-28T04:24:54.898Z] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[2021-04-28T04:24:54.898Z] [ERROR] 
[2021-04-28T04:24:54.898Z] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[2021-04-28T04:24:54.898Z] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[2021-04-28T04:24:54.898Z] [ERROR] 
[2021-04-28T04:24:54.898Z] [ERROR] After correcting the problems, you can resume the build with the command
[2021-04-28T04:24:54.898Z] [ERROR]   mvn <args> -rf :rbac-api-server
[Pipeline] echo
04:24:54  downstream validation failed on metadata-service
[Pipeline] echo
04:24:54  repolink:https://github.com/confluentinc/metadata-service/tree/6.2.x
```

**Comment by andrewegel** [comment]
> Looks fine other than the build error 😦

yeah thats an already occurring issue that should be fixed before we re-run the PR builder to check the downstream repos

**Comment by andrewegel** [comment]
Looks like MDS was addressed and we have a clean PR build now.

**Review by xjin-Confluent — APPROVED** [review]

**Review by ewencp — APPROVED** [review]

**Comment by elismaga** [comment]
we don't need to upgrade the version of jackson

**Pull request closed without merging**
