### PR TITLE
Upgrade spotbugs, easymock, powermock

### PR DESCRIPTION
**Pull request by xvrl**
- spotbugs 3.1.8 fixes the issue we saw in #169
- easymock 4.0.1 for JDK11 support
- powermock 2.0.0-rc3 for JDK11 support

### CODE REVIEW

**Comment by ijuma** [comment]
There's one change in EasyMock that can cause compiler errors, did you run a build via muckrake?

**Comment by xvrl** [comment]
@ijuma what change are you referring to? muckrake is currently not working.

**Comment by ijuma** [comment]
@xvrl See https://github.com/apache/kafka/pull/5846 for example. Have you tried running `./build.sh` locally with `muckrake`?

**Comment by xvrl** [comment]
@ijuma I verified the build succeeds now that https://github.com/confluentinc/kafka-rest/pull/509 has been merged.

**Pull request merged**
