### PR TITLE
Bump junit 4 version to latest version (4.13.2)

### PR DESCRIPTION
**Pull request by daniloqueiroz**

### CODE REVIEW

**Review by xvrl — APPROVED** [review]

**Review by andrewegel — CHANGES_REQUESTED** [review]
```
Downstream check failed on following repos:
ksql-master
kafka-connect-replicator-master
schema-registry-plugins-master
secret-registry-master
confluent-security-plugins-master
confluent-cloud-plugins-master
ce-kafka-http-server-master
ce-kafka-rest-master
metadata-service-master
blueway-master
newwave-master
connect-ksql-integration-master
cc-docker-schema-registry-master
cc-docker-messaging-master
```

Please investigate these failures. If they're due to the Junit change please post those PRs here before merging this change in.

**Comment by xvrl** [comment]
downstream changes are due to spotbugs failures in KSQL, and are unrelated to junit

**Review by andrewegel — APPROVED** [review]
Approved upon a PR build pass.

**Comment by andrewegel** [comment]
ksql is failing on:

```
17:19:03  [ERROR] Medium: Return value of java.util.function.BiFunction.apply(Object, Object) ignored, but method has no side effect [io.confluent.ksql.analyzer.AnalysisTest] At AnalysisTest.java:[line 150] RV_RETURN_VALUE_IGNORED_NO_SIDE_EFFECT
17:19:03  [ERROR] Medium: Return value of java.util.function.BiFunction.apply(Object, Object) ignored, but method has no side effect [io.confluent.ksql.analyzer.AnalysisTest] At AnalysisTest.java:[line 89] RV_RETURN_VALUE_IGNORED_NO_SIDE_EFFECT
17:19:03  [ERROR] Medium: Return value of java.util.function.BiFunction.apply(Object, Object) ignored, but method has no side effect [io.confluent.ksql.analyzer.AnalysisTest] At AnalysisTest.java:[line 191] RV_RETURN_VALUE_IGNORED_NO_SIDE_EFFECT
17:19:03  [ERROR] Medium: Return value of java.util.function.BiFunction.apply(Object, Object) ignored, but method has no side effect [io.confluent.ksql.analyzer.AnalysisTest] At AnalysisTest.java:[line 130] RV_RETURN_VALUE_IGNORED_NO_SIDE_EFFECT
17:19:03  [ERROR] Medium: Return value of java.util.function.BiFunction.apply(Object, Object) ignored, but method has no side effect [io.confluent.ksql.analyzer.AnalysisTest] At AnalysisTest.java:[line 170] RV_RETURN_VALUE_IGNORED_NO_SIDE_EFFECT
17:19:03  [ERROR] Medium: Return value of java.util.function.BiFunction.apply(Object, Object) ignored, but method has no side effect [io.confluent.ksql.analyzer.AnalysisTest] At AnalysisTest.java:[line 109] RV_RETURN_VALUE_IGNORED_NO_SIDE_EFFECT
17:19:03  [ERROR] Medium: Return value of java.util.function.BiFunction.apply(Object, Object) ignored, but method has no side effect [io.confluent.ksql.engine.rewrite.StatementRewriterTest] At StatementRewriterTest.java:[line 890] RV_RETURN_VALUE_IGNORED_NO_SIDE_EFFECT
17:19:03  [ERROR] Medium: Return value of Reduce.reduceArray(List, Object, BiFunction) ignored, but method has no side effect [io.confluent.ksql.function.udf.lambda.ReduceTest] At ReduceTest.java:[line 98] RV_RETURN_VALUE_IGNORED_NO_SIDE_EFFECT
17:19:03  [ERROR] Medium: Return value of Reduce.reduceArray(List, Object, BiFunction) ignored, but method has no side effect [io.confluent.ksql.function.udf.lambda.ReduceTest] At ReduceTest.java:[line 102] RV_RETURN_VALUE_IGNORED_NO_SIDE_EFFECT
```

The ksql/master "proper" job is not failing on these so on the surface this looks like this common change will impact things downstream. Checking the maven commands ran, the downstream check runs:

```
mvn --batch-mode -Pjenkins -DskipTests -Ddependency-check.skip=true -Djacoco.skip=true -Ddocker.skip-build=true install
```

The proper build runs

```
mvn --batch-mode -Pjenkins clean install dependency:analyze site validate -U -Ddocker.registry=.../ -Ddocker.upstream-registry=.../ -DBUILD_NUMBER=9068 -DGIT_COMMIT=8a11ac2189 -Ddocker.tag=dev-master-9068 -Ddocker.upstream-tag=master-latest 
```

If the former requires fixing (in jenkins-common), i'd like to know what it is.

**Comment by andrewegel** [comment]
As discussed offline, the spotbug issues are in ksql from the PR builder using Java11 instead of Java8. I'm fine with merging this in now that explanation has been given.

**Pull request merged**
