### PR TITLE
Upgrade Jackson to 2.10.2 and Avro to 1.9.2

### PR DESCRIPTION
**Pull request by kkonstantine**
Upgrade jackson and jackson-bom to the most recent versions to resolve known CVEs
Upgrade Avro to 1.9.2 in 5.4.x

### CODE REVIEW

**Comment by kkonstantine** [comment]
This PR is the equivalent of https://github.com/confluentinc/common/pull/247 and will help resolve CVEs in this release branch.

**Comment by kkonstantine** [comment]
Thanks @ijuma 
Indeed, recent versions such as 2.10.4 and 2.10.3 are without timestamp according to maven central: https://mvnrepository.com/artifact/com.fasterxml.jackson/jackson-bom

**Comment by ijuma** [comment]
Sounds good. The PR failed, not sure if related.

**Comment by arvindth** [comment]
As an FYI, when #247 was merged, there were some additional changes required in control center, and I believe in ksql & schema registry as well, since the 2.10 upgrade was not seamless.

**Comment by kkonstantine** [comment]
A closer read on the jackson release notes for [2.10](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10) showed that 2.10.4 introduced a breaking change that we probably don't want to adopt on a patch release (unless there's a more important reason to upgrade). 

Choosing `2.10.2` for now here also gives us alignment with the recent AK release branches that are currently in the phase of producing release candidates. 

@ijuma the build was broken due to a downstream failure in SR that was fixed here: https://github.com/confluentinc/schema-registry/pull/1517
But now it fails on the dependent PR in ksqlDB: https://github.com/confluentinc/ksql/pull/5725 so we'll probably have to merge here first. 

@arvindth thanks for the heads up. The respective PRs have already been issued/merged in the affected projects (same changes as in 5.5.x)

@ewencp good point. Given that the suggestion is now to upgrade to 2.10.2, we don't have a conflict with the blocker process in newer release branches.

**Comment by kkonstantine** [comment]
Same as before, the failure is due to a warning in ksqlDB: 
`ksql-5.4.x/ksql-engine/src/main/java/io/confluent/ksql/function/udf/json/ArrayContainsKudf.java:[42,24] disable(com.fasterxml.jackson.core.
JsonFactory.Feature) in com.fasterxml.jackson.core.JsonFactory has been deprecated`

This is fixed here: https://github.com/confluentinc/ksql/pull/5725

**Pull request merged**
