### PR TITLE
Bump confluent-log4j version 1.2.17-cp5

### PR DESCRIPTION
**Pull request by RamanVerma**

### CODE REVIEW

**Review by lbradstreet — APPROVED** [review]
LGTM once tests pass, thanks. Please improve the general commit message.

**Review by bob-barrett — APPROVED** [review]
LGTM, but we might want someone from tools to sign off

**Review by jhlee8 — APPROVED** [review]
LGTM (with successful PR builds)

**Comment by andrewegel** [comment]
metadata-service failing on

```
14:12:41  [INFO] -------------------------------------------------------------
14:12:41  [ERROR] COMPILATION ERROR : 
14:12:41  [INFO] -------------------------------------------------------------
14:12:41  [ERROR] /home/jenkins/workspace/ntinc_Contributors_common_PR-396/metadata-service-master/rbac-extractor/src/main/java/io/confluent/rbac/extractor/DeadLetterQueue.java:[16,32] package org.apache.logging.log4j does not exist
14:12:41  [ERROR] /home/jenkins/workspace/ntinc_Contributors_common_PR-396/metadata-service-master/rbac-extractor/src/main/java/io/confluent/rbac/extractor/DeadLetterQueue.java:[17,32] package org.apache.logging.log4j does not exist
14:12:41  [ERROR] /home/jenkins/workspace/ntinc_Contributors_common_PR-396/metadata-service-master/rbac-extractor/src/main/java/io/confluent/rbac/extractor/DeadLetterQueue.java:[29,24] cannot find symbol
14:12:41    symbol:   class Logger
14:12:41    location: class io.confluent.rbac.extractor.DeadLetterQueue
14:12:41  [ERROR] /home/jenkins/workspace/ntinc_Contributors_common_PR-396/metadata-service-master/rbac-extractor/src/main/java/io/confluent/rbac/extractor/DeadLetterQueue.java:[29,37] cannot find symbol
14:12:41    symbol:   variable LogManager
14:12:41    location: class io.confluent.rbac.extractor.DeadLetterQueue
14:12:41  [INFO] 4 errors 
14:12:41  [INFO] -------------------------------------------------------------
14:12:41  [INFO] ------------------------------------------------------------------------
14:12:41  [INFO] Reactor Summary for metadata-service 7.2.0-99999:
```

**Comment by niteshmor** [comment]
This will inadvertently include log4j2 in various CP artifacts, which we don't want right now. I think this should be reverted back 
@mkcops

**Comment by RamanVerma** [comment]
The build was failing in downstream validation but we decided to merge right now. Relevant discussion https://confluent.slack.com/archives/C02QXM7M1CY/p1639175079468300?thread_ts=1639157513.315900&cid=C02QXM7M1CY

**Pull request merged**
